### ISSUE TITLE
"Project on Floor" not working

### ISSUE THREAD

**Issue by sheosi** [HungryProton/scatter#10]
I've been trying to use the "project on floor" setting but it's not working, even in the demo scene, when I modify the "GrassMultimesh" enough for it to change it ends up ignoring any physics obstacles, this happens as well on my own scenes. The only useful information I've gotten are this errors shown on console:
`
scene/main/node.h:281 - Condition "!data.tree" is true. Returned: __null
scene/resources/curve.cpp:1056 - Index p_index = -1 is out of bounds (points.size() = 8).
scene/resources/curve.cpp:1076 - Index p_index = -1 is out of bounds (points.size() = 0).
`

**Comment by HungryProton** [comment]
Yesterday's PR should have fixed that, can you download the latest version and try again from this commit? 8c622bb80f84e7c49424076f8837f7e8724a3822

**Comment by sheosi** [comment]
Now is working well, thanks.
