### ISSUE TITLE
Load time / pop in (get notified when grass is loaded?)

### ISSUE THREAD

**Issue by sebastianrueckerai** [HungryProton/scatter#107]
I would like my player to start in a lush field made by scatter. Unfortunately it takes quite some seconds even on a fast PC to load in the grass. Is it possible to somehow load this before the scene starts or even get an event when the grass is ready so the player does not start in a half-build scene?

**Comment by HungryProton** [comment]
In the 4.0 version, you can listen to the `build_completed` signal on the Scatter node

**Comment by sebastianrueckerai** [comment]
Awesome, thanks! :)

**Comment by sebastianrueckerai** [comment]
Hey,

I am trying to implement your tip about the signal.
I have some weird behavior: If I connect the signal manually it works fine. 
However, if I try and connect all Scatter nodes automatically, the line `child.connect` will run but the connected function is never called will. If I connect the same function manually it works. Any idea why?

```
func _ready():
	for child in self.get_children():
		if child.has_signal("build_completed"):
			scatter_node_counter += 1
			if not child.is_connected("build_completed", _on_scatter_build_completed):
				child.connect("build_completed ", _on_scatter_build_completed)
	
func _on_scatter_build_completed():
	reported_scatter_builds += 1
	if reported_scatter_builds >= scatter_node_counter:
		print("SCATTER BUILT!")
```

The above code is in my root node.

**Comment by HungryProton** [comment]
If you've copy-pasted the code exactly as in your project, you have an extra space on the signal name in the `child.connect` call.

If you want to catch this kind of error when writing the code, Godot 4 have a new syntax for signals: 
```
child.build_completed.connect(_on_scatter_build_completed)
``` 

(in your case, since the child is not typed, the autocomplete wouldn't help much)

**Comment by sebastianrueckerai** [comment]
Ahhhh... that's what I get for coding so late! :D

Thanks for the tip about the signals, that is cool!

**Comment by sebastianrueckerai** [comment]
I tried to pause the game while scatter nodes are loading. I set the scatter nodes to always processing so I thought it would work.
It does not however, I don't receive their signal.
Any reason why they don't finish loading during pause even if they are set to always processing?

**Comment by HungryProton** [comment]
Seems to work on my end, is the script listening to the event also set to always process ?

**Comment by sebastianrueckerai** [comment]
I made a node that is a child my world node to handle the pausing.

Here is the code:
```
extends Node

var scatter_node_counter : int = 0
var reported_scatter_builds : int = 0

@onready var loading_screen = %LoadingScreen

func _ready():
	process_mode = Node.PROCESS_MODE_ALWAYS
	_wait_for_scatter_items_to_load()
	
func _process(_delta) -> void:
	if Input.is_action_just_pressed("pause"): # Tab
		get_tree().paused =false

func _on_scatter_build_completed() -> void:
	reported_scatter_builds += 1
	if reported_scatter_builds >= scatter_node_counter:
		get_tree().paused = false
		loading_screen.hide()
		
func _wait_for_scatter_items_to_load() -> void:
	for node in get_parent().get_children():
		if node.has_signal("build_completed"):
			node.process_mode = Node.PROCESS_MODE_ALWAYS
			scatter_node_counter += 1
			if not node.build_completed.is_connected(_on_scatter_build_completed):
				node.build_completed.connect(_on_scatter_build_completed)
	if scatter_node_counter > 0:
		loading_screen.show()
		get_tree().paused = true
```

I am setting the nodes to `PROCESS_MODE_ALWAYS` in the script just to be sure. I also set them to the same thing in the editor.
My workaround is to just set all other items to `PROCESS_MODE_DISABLED`which works. Still strange...
