### ISSUE TITLE
v4 use_instancing Mesh merging doesn't always work, prints errors

### ISSUE THREAD

**Issue by TokisanGames** [HungryProton/scatter#110]
v4 9cf4e7fdd7ec986212b8ecdb5dc0a1cc0993f17e
Godot 4.0.2

Some meshes work fine with use_instancing. Some do not. I have some from UE foliage packs that show fine when placing scenes, but do not show when use_instancing is turned on. This error message appears on the console in Godot 4.0.2:

```
ERROR: Condition "p_arrays[ai].get_type() != Variant::PACKED_BYTE_ARRAY" is true. Returning: ERR_INVALID_PARAMETER
   at: _surface_set_data (servers/rendering_server.cpp:507)
ERROR: Invalid array format for surface.
   at: (servers/rendering_server.cpp:975)
ERROR: Condition "err != OK" is true.
   at: add_surface_from_arrays (scene/resources/mesh.cpp:1602)
ERROR: Index p_idx = 0 is out of bounds (surfaces.size() = 0).
   at: surface_set_material (scene/resources/mesh.cpp:1723)
```

The attached file is one example of a mesh setup the same way other working meshes are, it will work placed as a scene, but not when it goes through the mesh merger code.

[lavandula040.zip](https://github.com/HungryProton/scatter/files/11321845/lavandula040.zip)

**Comment by HungryProton** [comment]
Looking into it, that merger function is long overdue for an update.
Thanks for the model that causes the issue.

**Comment by HungryProton** [comment]
Should be fixed, let me know if other models cause any issues.

**Comment by TokisanGames** [comment]
Works well, thanks! It also fixed the same issue with my ferns. I'll let you know if I come across anything else.

BTW, In brick.tscn you need to move the collision shape under the staticbody so collision works.

![image](https://user-images.githubusercontent.com/632766/234595588-aa2fe9cb-a35e-4aca-94d1-69ae61b25cbb.png)
