### ISSUE TITLE
Readme mentions specific license file for assets which does not exist

### ISSUE THREAD

**Issue by winston-yallow** [HungryProton/scatter#113]
The readme states:
> Most 2D and 3D assets in the demos folder are MIT, with a few exceptions. Refer to the LICENCE.md in the assets folder for more details.

However, there is no such file in the assets folder. I'm wondering if the license file was forgotten to add or if the readme is wrong and all models are MIT now?

**Comment by HungryProton** [comment]
I forgot to add it back, but there's almost nothing in this license file anymore since I remade every 3D assets. It's only about the textures from textures.com now. I'll put it in the readme directly.
