### ISSUE TITLE
ScatterItem can't define items(scenes) which have children that are not Node3D or subclasses of it

### ISSUE THREAD

**Issue by BionicBlueBell** [HungryProton/scatter#116]
**Steps to reproduce**
1. Open a scene with the parent node being a MeshInstance3D
2. Add in an animation player & save the scene
3. In a new scene, add a ProtonScatter node, and in its ScatterItem node define its path to the saved scene

**Comment by BionicBlueBell** [comment]
I guess this isn't an issue because the addon is only meant to work with raw assets

**Comment by HungryProton** [comment]
You can set anything in the ScatterItem, even if it's not a MeshInstance3D as long as you're not using instancing (which is enabled by default)

(When instancing is on, Scatter creates a multimesh to speedup the scene creation and rendering, but that only supports MeshInstances)

**Comment by BionicBlueBell** [comment]
Yes, I figured this out recently, and it works great for me. Thank you for making such a fantastic addon for free <3
