### ISSUE TITLE
Thread updates broke 4.0

### ISSUE THREAD

**Issue by TokisanGames** [HungryProton/scatter#118]
4.0.2 produces errors in your demo and any Scatter node w/ threading enabled is broken. Debug/disable_thread does allow it to load in 4.0.2:

```
SCRIPT ERROR:SCRIPT ERROR: Invalid call. Nonexistent function 'set_thread_safety_checks_enabled' in base 'Thread'.
 Invalid call. Nonexistent function 'set_thread_safety_checks_enabled' in base 'Thread'.
          at: _rebuild_threaded (res://addons/proton_scatter/src/scatter.gd:258)
          at: _rebuild_threaded (res://addons/proton_scatter/src/scatter.gd:258)
SCRIPT ERROR: Invalid call. Nonexistent function 'set_thread_safety_checks_enabled' in base 'Thread'.
SCRIPT ERROR:SCRIPT ERROR:          at: _rebuild_threaded (res://addons/proton_scatter/src/scatter.gd:258)
 Invalid call. Nonexistent function 'set_thread_safety_checks_enabled' in base 'Thread'.
 Invalid call. Nonexistent function 'set_thread_safety_checks_enabled' in base 'Thread'.
          at:           at: _rebuild_threaded (res://addons/proton_scatter/src/scatter.gd:258)
_rebuild_threaded (res://addons/proton_scatter/src/scatter.gd:258)
```

**Comment by HungryProton** [comment]
Fixed in 550fb1bd6e7ab33075a5ac2218394ddb0c70d124

**Comment by TokisanGames** [comment]
Hey Hungry, we released Terrain3D
https://github.com/outobugi/Terrain3D

We included a Scatter modifier to detect the ground.
https://github.com/outobugi/Terrain3D/blob/main/project/addons/terrain_3d/extras/project_on_terrain3d.gd

And I mentioned you in the promotional video:
https://www.youtube.com/watch?v=Aj9vWIEaFXg

We're finally migrating off of 4.0 so shouldn't complain any more about it. Only 4.1.

**Comment by HungryProton** [comment]
Congrats on the launch! 
Let me know if you have issues with custom modifiers, or if I can do anything to improve the experience!

I plan on keeping scatter backward compatible with 4.0 for a while, too.
