### ISSUE TITLE
In "Distribute Along Path", "Align to Path" parameter only affect the Y axis

### ISSUE THREAD

**Issue by HungryProton** [HungryProton/scatter#13]

**Comment by addmix** [comment]
I could see a use case for only rotating along the Y axis, keeping it as an option would be greatly appreciated

**Comment by southpaw-decoy** [comment]
I would love the option to toggle rotation for each axis separately.

**Comment by addmix** [comment]
> I would love the option to toggle rotation for each axis separately.

I can work on implementing that functionality tomorrow.

**Comment by HungryProton** [comment]
> I can work on implementing that functionality tomorrow.

I have a branch where I started this feature but never finished it. I can push it if you want a starting point, but I don't remember why I gave up midway.

**Comment by HungryProton** [comment]
I pushed what I started on the branch `issue/13`

There are three options, `align_y_axis` rotates the object, so the forward vector faces the curve direction.
`align_x_axis` should take care of the up and down rotation but this doesn't work at all.
`align_z_axis` takes care of the tilt by rotating around the Z axis but this is not supported as there's no way to change the curve's tilt from the editor anyway.

By the way, the fence object in the example scene is aligned on its x-axis so by default, the alignment will be wrong. That's easy to solve with the `Add Offset` modifier by adding a local 90° rotation. This breaks as soon as tilt is introduced so I wonder if we shouldn't simply ignore that tilt exists, or find another solution.

**Comment by addmix** [comment]
fixed in #28

**Comment by addmix** [comment]
#28

**Comment by southpaw-decoy** [comment]
I just tried the fix and it appears to be working correctly to me. Thanks for working on this!
