### ISSUE TITLE
scatter creates orphan nodes

### ISSUE THREAD

**Issue by ignisghost** [HungryProton/scatter#131]
Hey mate, the version of the add on that is currently on assetlib for godot 4.x , is creating a huge amount of orphan nodes. I have found some issues with the usage of ProtonScatterItem-> get_item(). This method creates and instance of an item but the way you use it, leaves orphan nodes.
For example, in scatter_util.gd you create an item and then you duplicate it for further use, but you forget to free them, resulting in leaks

static func get_collision_data(item: ProtonScatterItem) -> StaticBody3D:
	var static_body := StaticBody3D.new()
	var source: Node3D = item.get_item().duplicate(0)     # <<< this results in orphan nodes. 
       # rest of code

instead I did:
static func get_collision_data(item: ProtonScatterItem) -> StaticBody3D:
	var static_body := StaticBody3D.new()
	var it = item.get_item()
	var source: Node3D = it.duplicate(0)
	it.free()

and like that, orphan nodes in my project which uses your add on, were reduced by 30% . 
I found more occasions in which you do this thing with the duplicate or returning before freeing those orphan nodes you create. 
I still have some orphan nodes left because I haven't yet found all the issues in the add on. 
I hope this helped!

**Comment by HungryProton** [comment]
I fixed some of these today, you can try the latest version from the Github repo (asset lib updates take some time).

I'm still tracking down the last orphans, I'll post an update here once it's done.

**Comment by ignisghost** [comment]
Yeah, it is better now. I think there are only one or two lines left that cause the issue. I will try to find them too.

**Comment by HungryProton** [comment]
Alright, I think this issue is fixed. At least, the showcase scene doesn't have any orphans anymore. If you could try 598cb7e689866f3f6057a1b396c0248cacb6a1cc on your project and confirm it's fixed, that would be great!

**Comment by HungryProton** [comment]
> Yeah, it is better now. I think there are only one or two lines left that cause the issue. I will try to find them too.

The `get_merged_meshes_from` function was missing a queue_free. It should be good now

**Comment by ignisghost** [comment]
Perfect. Zero orphan nodes. That was the method I was going to check tomorrow!
