### ISSUE TITLE
Project on colliders causes main thread to hang

### ISSUE THREAD

**Issue by Norodix** [HungryProton/scatter#132]
The project on colliders modifier causes the main thread of the editor to hang.
This is mostly noticeable on larger scatters with lost of transforms.

The problem seems to occur in the main `_process_transforms` function after calling execute on the phyics helper.
If I add artificial high cpu load delays in the thread the only place that it seems to hang the main thread is after returning from `await physics_helper.execute(queries)`.
Time wasters before this call delay the execution of the modifier but do so on a separate thread as expected.
Time wasters after this call hang the main thread of the editor.

I don't understand yet why hanging on a separate thread can hang the editor.

**Comment by Norodix** [comment]
One thing I noticed is `remove_at` is used to remove invalid points from the array. This method is slow for large arrays, so it might be the reason the modifier is slow for larger scatters. This does not explain why the main thread waits for this thread to finish, but it makes the freeze caused by the real issue worse.

**Comment by HungryProton** [comment]
I'll look into this. Replacing remove_at by something else should be easy, but I'm not sure why the main thread would hang.

**Comment by Norodix** [comment]
Yes, remove_at is just an optimization, the real problem is the hanging of the main thread. I just thought I write it down, not to forget it. It could be significant for larger scatters.

**Comment by HungryProton** [comment]
Well, that's not how I expected await to work:  

![image](https://github.com/HungryProton/scatter/assets/52043844/d9f18698-520d-4d16-a1da-5d4d66aac2dd)

I'll have to ask around, check if this is a bug or by design.

Because this means everything after the await gets executed in the main thread, and that also include the other modifiers in the stack, after this one.

**Comment by Norodix** [comment]
Nice find! Seems strange to me too.
I thought of something similar but discarded the idea because other places use await too that seem to work on the separate thread.
For example `modifier_stack.start_update` also uses await and this is the first function that is called in the thread.
Quite strange.

I'm not 100% sure but I think we have seen degraded performance using other modifiers after project. But usually project is the last one, so it might have hidden this problem so far.

**Comment by Norodix** [comment]
It might be because using the return after an await makes it a coroutine.
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#awaiting-for-signals-or-coroutines

There is some info here but no further explanation that coroutine would interfere with threading.
Maybe changing up things a bit to avoid using return of await could solve the problem.

**Comment by HungryProton** [comment]
Okay this is a regression, the bug does not occur in 4.0.3. I'll open an issue and hope for a fix.

**Comment by Norodix** [comment]
There doesn't seem to be much activity on the root cause of this issue.
It also seems like a complex issue with the engine / gdscirpt itself, so I'm not sure when it will be resolved.

I have been messing with this a bit and it is not very difficult to eliminate all uses of await from inside the thread.
As far as I can tell the only important use of await is in the physicshelper, where the thread waits for the main thread to process the raycasts. Eg. Instead of waiting for job completed siganl it can be replaced as such:
```
while not job_completed_var:
	waitcounter += 1
	OS.delay_msec(100)
	if waitcounter == 20:
		print("too many tries, it failed")
		return [] 
```
Or something similar.

While it is much uglier than using signals and await the performance boost is very significant. It's very nice how the scatter is completed without any pause, especially in-game. 

Do you think it is worth changing things to use this pattern or similar instead of await, or is it better to wait for the engine to fix the issue?

**Comment by HungryProton** [comment]
Someone referenced an even older issue from last year, so I'd say let's do the workaround and remove it later if it's not needed anymore. 

I'm experimenting a bit on my side and it seems to work fine. I'll push a commit later once I'm done with all the safety checks.

**Comment by HungryProton** [comment]
I pushed a fix, I added a check just in case the execute function gets called from the main thread, so it can fall back on await (otherwise the whole editor will freeze).

Seems to work fine in the showcase scene and a stress test scene, but it would be great to test it more.

**Comment by Norodix** [comment]
Seems to work nice.
I don't 100% understand what determines whether an await will drop it back to the main thread or not.
I guess it has something to do with those corutine error messages but I'm not sure. 
Anyway, its nice how it handles main thread too.
Thanks for the fix!

**Comment by HungryProton** [comment]
I'm not 100% sure either, but so far, every signal emitted by the main thread causes the co-routine to resume on the main thread. Waiting for `ready`, `physics_frame`, `process_frame` and `create_timer().timeout` all causes this issue. There's probably other cases too, but I haven't encountered them while debugging this specific issue.

**Comment by Norodix** [comment]
I recently learned that signals call their callbacks immediately instead of at the end of a frame or something (which I assumed for some reason).
Maybe internally it works by the signal emitter directly calling the connected callbacks. It would make sense that the emitter's thread is the one working then since that is the one that calls the function. But I am just guessing, for now the important thing is it works.

**Comment by HungryProton** [comment]
When connecting signals manually, you have the option to make them call their callbacks immediately, deferred or once, but with await I believe only the immediate mode is used, so yeah that's probably where that comes from.
