### ISSUE TITLE
AssetLib icon?

### ISSUE THREAD

**Issue by Norrox** [HungryProton/scatter#133]
Im sorry but this won't cut it :D
![Skärmbild 2023-07-18 121252](https://github.com/HungryProton/scatter/assets/13393087/13700ba1-e611-4902-b776-7e60f1621471)

feel free to use this one if you like <3
![christoffer_logo_minimalistic_addon_for_scatter_rocks_and_plan_83ffe95e-51bb-43fd-8ef2-00ea6f1b7f5d](https://github.com/HungryProton/scatter/assets/13393087/8d39add8-0d70-4a70-b8a7-05b45bc88469)

or these

![christoffer_minimalistic_icon_dots_and_crosses_geometry_4833966c-b238-4cdb-a788-72bd484709ae](https://github.com/HungryProton/scatter/assets/13393087/561d82fb-91e2-4c9a-b6ab-da2b138ee6b0)
![christoffer_minimalistic_icon_dots_and_crosses_geometry_bfe6c4a1-dc92-448d-99b0-358c641b1a17](https://github.com/HungryProton/scatter/assets/13393087/f5f38632-432f-4746-b469-fa9c77b0d7b7)

**Comment by HungryProton** [comment]
What's wrong with the current logo? :stuck_out_tongue: 

I like the second one! I'll try to make something that works on a small scale based on this.

**Comment by HungryProton** [comment]
Asset lib icon was updated.
