### ISSUE TITLE
ProtonScatter generates large amounts of invalid UID warnings in Godot 4.1.1 

### ISSUE THREAD

**Issue by Scuas** [HungryProton/scatter#136]
Hi, I recently installed a fresh version of ProtonScatter one week ago while updating my Godot project to 4.1.1.

I noticed the addon now generates a distracting amount of warnings relating to invalid UIDs. 
Pictured below is some of the output from spawning the default protonscatter node in a blank scene with a floor, 47 lines relating to UIDs were generated in total.

![image](https://github.com/HungryProton/scatter/assets/66699973/08f7bc36-6c6b-48b6-8006-2769fb7817ac)

**Comment by HungryProton** [comment]
That's an engine bug, I don't think I can fix that on my end.

**Comment by florianvazelle** [comment]
I've noticed the same problem and I have the impression that the solution would be to commit the `*.import` files, as recommended [here](https://github.com/godotengine/godot/issues/68661#issuecomment-1499062674) (what I'm currently testing on my side).

**Comment by HungryProton** [comment]
Committing the import files (after reimporting and resaving everything) seems to work, let's hope that doesn't break anything else.
