### ISSUE TITLE
Add ability to disable a scatter

### ISSUE THREAD

**Issue by Norodix** [HungryProton/scatter#139]
I am thinking maybe it would be a good idea to add an easy way to disable a scatter.

On larger scenes it could help save memory to only enable the scatters that are near the player.
During editing it could help loading times. 
It would enable the user to load scatters one by one to make loading the level smoother.
Maybe other things I did not think of.

Do you think this would be beneficial or just add clutter to the ui?

**Comment by HungryProton** [comment]
It could be useful to add a new `enabled` parameter that just blocks the rebuild function when disabled. This way, you can actually decide when to actually rebuild the scatter node.

Turning it off after the initial rebuild only help with memory usage if it also clears the results (forcing you to recalculate everything next time it's enabled).

I'm not sure if it's going to help with editing. There's already `Force rebuild on load` you can disable, so it doesn't rebuild automatically when opening the scene, and this works well with the cache node, so you still get instant results.

Automatically enable / disable the node based on the player distance should be up to the end user, though. Projects are usually distinct enough that a generic solution that works everywhere isn't feasible.

**Comment by Norodix** [comment]
So I agree that the user should enable and disable scatters based on whatever criteria.
I was thinking to create an easy to use interface for that.
Like a single option to clear and disable everything and to re-enable.

Regarding editing I notice that the `force_rebuild_on_load` option does not seem to do anything.
It seems that the transform changed notification is called when loading the scene so opening the scene in the editor recalculates everything anyway.
What's more, is that it seems when I open the scene everything is calculated 2x.

**Comment by HungryProton** [comment]
That should be fixed now, the rebuild functions were called from some variable setters (which are called on scene load). Now, they skip the first call if it happens before the _ready() function.

**Comment by HungryProton** [comment]
An extra parameter on the scatter node should be enough, I think, no need to disable every modifier and make a custom UI for that.

**Comment by Norodix** [comment]
I still seem to get 2 rebuilds when loading the scene.
One is definitely from `NOTIFICATION_TRANSFORM_CHANGED`.
The other's source I have not found yet.

**Comment by Norodix** [comment]
The other is called from `_on_transforms_ready` I think

**Comment by HungryProton** [comment]
> I still seem to get 2 rebuilds when loading the scene. One is definitely from `NOTIFICATION_TRANSFORM_CHANGED`. The other's source I have not found yet.

What if you put these two lines at the begining of the _notification function?
```gdscript
func _notification(what):
	if not is_ready:
		return

	match what:
		[...]
```

**Comment by Norodix** [comment]
It still runs. I guess for some reason the node is moved in place by the editor after its ready.

**Comment by Norodix** [comment]
Oh, interestingly these things don't run when I open the scene.
I might have been wrong to test by switching tabs in the editor between scenes. 

So the problem is a bit different now (i guess after your fixes): a rebuild is forced when you switch tabs.
The is_ready variable is already set then so the notification and the transforms ready signal run the update for all scatters in the scene.

**Comment by HungryProton** [comment]
I think there's a signal somewhere to detect tab switching, then it's a matter of ignoring the first move notification following that signal, I guess.

**Comment by Norodix** [comment]
Added in https://github.com/HungryProton/scatter/pull/143
