### ISSUE TITLE
Scene with subscenes aren't placed correctly

### ISSUE THREAD

**Issue by ToxicCrack** [HungryProton/scatter#145]
Hello, i have a problem with placing a scene with this addon.
This is the scene:
![image](https://github.com/HungryProton/scatter/assets/3591570/9fc84b4c-e11f-4bf3-a07e-2c68d8904f43)

And this is how it's placed:
![image](https://github.com/HungryProton/scatter/assets/3591570/079dacb4-3cbe-4045-a10b-fe2f2055f792)

Why is the mine on the ground? Do I do something wrong?

**Comment by HungryProton** [comment]
Go to the `ScatterItem` node, under the source options, disable `ignore position`, see if that helps.

If you don't plan to place more than a few hundred of them, or if you have scripts attached to this scene, disable instancing under the main scatter node, under Performance > Render mode, select `Create copies`

**Comment by ToxicCrack** [comment]
Create copies did the trick! Thank you!
