### ISSUE TITLE
How to use use_insancing?

### ISSUE THREAD

**Issue by ColormaticStudios** [HungryProton/scatter#146]
This isn't an issue with the code, but I can't find out how to make "use instancing" work. I have discovered that the multimeshes are created properly, but no objects are being displayed.

**Comment by ColormaticStudios** [comment]
I figured out the problem, apparently multimeshes can't handle complex geometry.

**Comment by HungryProton** [comment]
What do you mean by complex geometry? Multimeshes should be able to handle any type of Mesh (or combination of meshes, since it merges them together when necessary)
