### ISSUE TITLE
toggle visibility of nodes

### ISSUE THREAD

**Issue by peterpants2** [HungryProton/scatter#147]
Is there a way to only have the 3d gizmos visible if an object is selected? if I have 10 different proton scatter shapes setup the scene view starts looking cluttered.

**Comment by HungryProton** [comment]
Not yet, but I'm working on a fix.

**Comment by HungryProton** [comment]
This is now the default behavior from version e7899a1ac2f76daab680f06198112093753577db

There's also a project setting that can be enabled to force the gizmos to always show if necessary.
