### ISSUE TITLE
Improving assetlib install

### ISSUE THREAD

**Issue by TheDuckCow** [HungryProton/scatter#148]
I started down the path of making a PR, but then realized you probably have opinions on which branch(es) to base it on, so writing the suggestion here first. Happy to make a PR on one or more branches if you like, or feel free to run with it yourself.

A few export-ignore are already used which is great, but there's still a few files and a folder that end users wouldn't want:

<img width="720" alt="Screen Shot 2023-08-05 at 10 34 34 AM" src="https://github.com/HungryProton/scatter/assets/2958461/7e1662ff-1e8c-4f13-a5db-12ef3eaffaff">

This change I think would improve it so someone can install all files with confidence:

```diff
diff --git a/.gitattributes b/.gitattributes
index c51f7e1..2213bdc 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -8,3 +8,6 @@
 /project.godot      export-ignore
 /icon.png          export-ignore
 /*.import          export-ignore
+/logo.png       export-ignore
+/logo.svg       export-ignore
+/.github        export-ignore
```

We did the same recent audit in our [road generator addon](https://github.com/TheDuckCow/godot-road-generator/issues/113), little things like this go a long ways :)

**Comment by HungryProton** [comment]
Right I haven't updated this file in a long time. Thanks for the input!
