### ISSUE TITLE
Project setting physics/3d/run_on_separate_thread breaks scatter

### ISSUE THREAD

**Issue by Norodix** [HungryProton/scatter#150]
Turning on the `physics/3d/run_on_separate_thread` setting in the project breaks scatter in some cases.
It is not very consistent. I guess it is a race condition.

I found that `get_direct_space_state()` returns null in case the world is not initialized when it is called.

It seems to me that moving `_space_state = get_tree().get_root().get_world_3d().get_direct_space_state()` in `physics_helper.gd` to the `_physics_process` solves this problem. This obviously means that the _space_state variable is not cached but updated at every call, but I don't think that is a very significant overhead.

**Comment by HungryProton** [comment]
We can move it to physics process, shouldn't be an issue.

**Comment by HungryProton** [comment]
Thanks for the report! Feel free to reopen if you manage to reproduce the issue
