### ISSUE TITLE
Scatter Cache Default Folder is Wrong

### ISSUE THREAD

**Issue by spiderbyte87** [HungryProton/scatter#154]
After hours banging my head against the wall, I randomly checked the file path and noticed that the default path is res://addons/proton_scatter/cache/...

when it should be res://addons/proton_scatter/src/cache/...

It's missing the 'src' folder, which was causing the cache to not load (obviously). As soon as I changed the path, everything worked as expected. I have to go back and revert my code so I'm not doing all the wazoo crap I was trying to get around the cache not loading now.

**Comment by HungryProton** [comment]
It's not missing the 'src' part, it's missing the actual cache folder, apparently. `src/cache` only stores the source code for that. But it never checks if the cache folder actually exists first. I'll push a fix.

**Comment by HungryProton** [comment]
In the meantime, you can manually create the `addon/proton_scatter/cache` folder and it should work as expected.
