### ISSUE TITLE
Unable use my own scenes with ScatterItem.

### ISSUE THREAD

**Issue by ghost** [HungryProton/scatter#167]
Hi!:) I'm for some reason unable to use by own scenes in ScatterItem. I'm trying to scatter the plant model in the bottom right, but putting the scene path into the ScatterItem doesn't generate anything but empty air. The bricks, and all other assets that come with the plugin work fine though. Any ideas of what's causing it to not work?:)

![Screenshot from 2023-10-05 11-39-32](https://github.com/HungryProton/scatter/assets/61879422/464b0e8b-a3d5-468c-945d-e16b2c37e045)

![Screenshot from 2023-10-05 11-45-20](https://github.com/HungryProton/scatter/assets/61879422/c9367b55-b0bc-4d5d-9178-f91acba940d5)

Settings for ScatterItem; only changed Path:

![Screenshot from 2023-10-05 11-45-39](https://github.com/HungryProton/scatter/assets/61879422/ab932829-0134-42b2-9b76-f280cf9b0404)

My scene for the plant model:

![Screenshot from 2023-10-05 11-47-02](https://github.com/HungryProton/scatter/assets/61879422/74e86669-2e18-4a9b-b10f-0aab69db7c0b)

**Comment by TokisanGames** [comment]
* Try removing the bricks scatter item and just have your plant. 
* Change the proportion so that all scatteritems summed equals 100. If the ferns are at 100 your cubes are probably also 100. That's 200% of 100.
* Use Hungry's demo and place your own assets inside of his preconfigured scatteritems. If that doesn't work your asset scenes are the problem. If it does, your scatter configuration is the problem.

**Comment by ghost** [comment]
Just having the plant's leves me with nothing (here all scatter sums == 100):

![Screenshot from 2023-10-05 15-10-18](https://github.com/HungryProton/scatter/assets/61879422/d2b4261e-5e72-40f9-9c95-089e1e0043a0)

Replacing the grass in the scene with my assets leaves me with this ^^':

![Screenshot from 2023-10-05 15-11-53](https://github.com/HungryProton/scatter/assets/61879422/b42f8813-153f-40b9-9783-135279d097b0)

So, any ideas on what about my asset scene causes the problem?

![Screenshot from 2023-10-05 15-13-52](https://github.com/HungryProton/scatter/assets/61879422/98861d3f-362c-431d-89b1-1587da032a63)

**Comment by Xtarsia** [comment]
An odd one, but check if something in your scene has a big scaling factor? It may actually be rendering but so small that it doesn't even fill 1 pixel.

Sometimes I've imported models and the parent node has 100x scale, and the actual mesh is tiny.

You can uncheck "ignore scale" etc in the scatter object if that is the case.

Also, nice to know exactly what "proportion" does!

**Comment by TokisanGames** [comment]
Duplicate Hungry's cube scene, get it working in scatter. Add your plant to it. Piece by piece take over this scene until you figure out the cause.

**Comment by ghost** [comment]
> Sometimes I've imported models and the parent node has 100x scale, and the actual mesh is tiny.

That was the problem! Thank you! Now i just gotta set "Scale Multiplier" = a casual 10,000 xD

**Comment by ghost** [comment]
Tho, the shadows be looking weird:/

... wait, i fixed it! changed back the scaling and changed "Render Mode" to "Create Copies".
