### ISSUE TITLE
Unclear why some meshes are underground and some aren't

### ISSUE THREAD

**Issue by BalJoseph** [HungryProton/scatter#172]
From the screenshot displayed, it shows that the bricks have half of the mesh clipping underground, while the bushes are rendered correctly.

![image](https://github.com/HungryProton/scatter/assets/48828516/7d034a64-4cb1-47ee-9442-025746613b85)

What is it that determines whether a mesh will be clipping or not?

**Comment by TokisanGames** [comment]
Look at where the origin point is on the objects. It's probably right in the center of the box, since they're all rotated around it.

**Comment by BalJoseph** [comment]
Yeah I thought about that, and while it is that by default the origin of the bricks is in the center, when I move the mesh above the origin the bricks' position remains unchanged in the Scatter.

I've also tried experimenting with different meshes and unfortunately the problem persists.

![image](https://github.com/HungryProton/scatter/assets/48828516/ea0f2fd0-b87a-48f1-85db-ee0747c8f7a0)

![image](https://github.com/HungryProton/scatter/assets/48828516/ed0d4478-90c6-4b26-8dcd-757153f60f71)

**Comment by HungryProton** [comment]
It's the origin of the MeshInstance itself. If you want to keep the offset, you need to turn off "Ignore Position" in the ScatterItem options 
![image](https://github.com/HungryProton/scatter/assets/52043844/f9c3365b-467f-44be-8d7f-ac13ef47371d)

**Comment by BalJoseph** [comment]
Thank you for clarifying what these settings are used for. I've tried turning these settings off but it seems that the position remains unaffected.

![image](https://github.com/HungryProton/scatter/assets/48828516/09d5907b-a117-4c86-9627-6e6ae1dad591)

I don't know if I'm doing something else wrong so I've attached another screenshot of the structure of the item I'm scattering.

![image](https://github.com/HungryProton/scatter/assets/48828516/7f743985-56cd-480a-a586-b7b76bb960df)

**Comment by HungryProton** [comment]
Oh right, that doesn't work anymore because of a recent commit.
Ignore the origin, and at the end of your modifier stack, put an "Edit Position" modifier and move everything up.

**Comment by BalJoseph** [comment]
I see, that's quite a shame. Does this mean that I need to put each item which requires an offset in its own Proton Scatter?

**Comment by HungryProton** [comment]
For now, it's either that, or not relying on primitive meshes and putting the offset in the mesh directly (not just moving the MeshInstance node, but the actual mesh data).

**Comment by BalJoseph** [comment]
Understandable, thank you for your help
