### ISSUE TITLE
Documentation: How to create a ScatterItem scene

### ISSUE THREAD

**Issue by fredrik779** [HungryProton/scatter#175]
Thanks for a great addon! :-)

I've been trying to add my own animated GLB object as a ScatterItem. It's created in Blender. I'm new to Godot 3D.

When reading other issues here, I understand that the addon needs a raw scene (i.e. a .tscn file). Also it seems like the GLB object seems to be added in a certain way to the tscn scene.

In my own scene it looks like this, and it doesn't work:
![image](https://github.com/HungryProton/scatter/assets/56190055/3e49e16f-191b-4dca-b8e4-c73787984717)

Error: "Invalid type in function 'get_all_static_bodies_from' in base 'GDScript'. The Object-derived class of argument 1 (AnimationPlayer) is not a subclass of the expected argument class."

The demo assets work (however both grass objects are all white), and they look like below (also using a GLB file):
![image](https://github.com/HungryProton/scatter/assets/56190055/a614da04-38ed-4bbc-99c4-3053b0dc34e9)

I tried creating a tcsc file manually in a text editor but didn't succeed. Copied text from a demo scene file, end result looks like below and get same error:
![image](https://github.com/HungryProton/scatter/assets/56190055/686bd945-9c02-4299-a162-3d80d66c2972)

I only get this issue when attempting to use a tscn scene that contains an animation.
 
It would be great if there was a guide in the documentation how to create a custom animated GLB object to be used as ScatterItem. If this is a generic Godot task not related to this addon it would be great with a pointer to the Godot documentation.

Possibly does the Blender project need to be setup in a certain way, when including animations?

Versions:
Blender 4.0
Godot 4.1.3
Scatter 4.1 (from asset store)

**Comment by HungryProton** [comment]
There's nothing wrong with your scene, that's a bug from the addon.
Should be fixed in the latest version (9cbdd801f4ef6c77140e84ed9b0d96df2c6c5bb1), you can download the zip from GitHub directly while the asset lib version is updated. 

Remember to change the render mode from `use instancing` to `create copies` in the scatter node too, animation doesn't work with instancing.

**Comment by fredrik779** [comment]
It worked, thanks a lot! :-)

**Comment by fredrik779** [comment]
How did you create the GLB files in the demo so that their animation is played after being scattered?

My scene is added the output, but doesn't play the animation. The animation works when adding the same scene directly in a scene. My scene contains an animated tree created with the Sapling Tree Gen. I've been looking into options in Blender, opening GLB file in text editor, open TSCN file in editor etc with no luck.

**Comment by HungryProton** [comment]
The demo animations are driven by a vertex shader, but in your case, you have an AnimationPlayer node so it's a bit different.

If you are using `Render mode: Create copies` in the ScatterNode, then it should just work, as long as something in your scene is actually triggering the animation. Either with the autostart property (on the AnimationPlayer track), or with a script.

**Comment by fredrik779** [comment]
That explains it, thanks again!
I realize that my game will definately need shader based trees.
