### ISSUE TITLE
set_icon @ parameter_node_selector.gd:67 appears to break NodePath selector (and Terrain3D selector)

### ISSUE THREAD

**Issue by nanodeath** [HungryProton/scatter#176]
Hi there,

As reported here https://github.com/TokisanGames/Terrain3D/issues/287, this line appears to be broken:

https://github.com/HungryProton/scatter/blob/9cbdd801f4ef6c77140e84ed9b0d96df2c6c5bb1/addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd#L67

When pulling in the [Terrain3D selector](https://github.com/TokisanGames/Terrain3D/blob/67c86c6a285281b100e297579716574182099d73/project/addons/terrain_3d/extras/project_on_terrain3d.gd), it defines a [NodePath parameter](https://github.com/TokisanGames/Terrain3D/blob/67c86c6a285281b100e297579716574182099d73/project/addons/terrain_3d/extras/project_on_terrain3d.gd#L35-L37) for specifying the Terrain3D node:

```gdscript
var p := documentation.add_parameter("Terrain Node")
p.set_type("NodePath")
p.set_description("Set your Terrain3D node.")
```

### Expected

Using the custom modifier (as described at the top of the directions in that file) should enable me to click on the Terrain Node field and select my Terrain3D node.

### Actual

I get a dialog that looks like this:

![image](https://github.com/HungryProton/scatter/assets/10625/90440298-dafb-4d60-898e-af8ea6cfa7ce)

Additionally, I see this error in the Godot Output console:

```
res://addons/proton_scatter/src/stack/inspector_plugin/ui/modifier/components/parameter_node_selector.gd:67 - Attempt to call function 'get_icon' in base 'null instance' on a null instance.
```

### Workaround

As mentioned in the Terrain3D ticket linked at the start, commenting out the offending line (containing `node_item.set_icon(0, theme.get_icon(node.get_class(), "EditorIcons"))`) and restarting Godot causes the dialog to be fully populated.

**Comment by nanodeath** [comment]
The following seems to work better than the aforementioned workaround:

```gdscript
func _populate_tree() -> void:
	_tree.clear()
	var scene_root: Node = get_tree().get_edited_scene_root()
	
	# NOTE Simplified editor_theme lookup
	var editor_theme = EditorInterface.get_editor_theme()

	_create_items_recursive(scene_root, null, editor_theme)


func _create_items_recursive(node, parent, theme) -> void:
	if parent and not node.owner:
		return # Hidden node.

	var node_item = _tree.create_item(parent)
	node_item.set_text(0, node.get_name())
	node_item.set_meta("node", node)
	# NOTE Check icon exists first; Terrain3D for example doesn't have an icon 
	if theme.has_icon(node.get_class(), "EditorIcons"):
		node_item.set_icon(0, theme.get_icon(node.get_class(), "EditorIcons"))

	for child in node.get_children():
		_create_items_recursive(child, node_item, theme)
```

[These docs](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-private-method-get-plugin-icon) mention `EditorInterface.get_editor_theme()`.

---

I'm not sure if we want to simply have _no_ icon, or have the default Node icon, if none is present.

Here's what Terrain3D looks like in the popup:

![image](https://github.com/HungryProton/scatter/assets/10625/772dc4d9-a50d-439d-8f5f-18b8d0e56d66)

And here's what it looks like in the Scene/Project panel:

![image](https://github.com/HungryProton/scatter/assets/10625/9c071c66-ad00-4d97-82ea-dca9cd328419)

**Comment by HungryProton** [comment]
Thanks for the report ! Feel free to reopen if the issue persists.

**Comment by nanodeath** [comment]
Well, I'm using 4.2, so the 4.2 branch looks fine to me 😄

I'm still a bit worried about the 4.1 branch, though. The original error was `Attempt to call function 'get_icon' in base 'null instance' on a null instance.`, which was happening not because the icon didn't exist, but because the `theme` object itself was null. Maybe that way of getting the theme works in 4.1 but returns null in 4.2? That's the optimistic take, anyway.

**Comment by HungryProton** [comment]
That's what's happening yes, `EditorInterface` was turned into a singleton in 4.2, so the old 4.x code doesn't work in the latest version anymore. 

I don't know yet how long I'm going to keep the older 4.x compatibility, though, but it should just work for now.
