### ISSUE TITLE
How to disable orange box displaying scatter shape?

### ISSUE THREAD

**Issue by Preston-Harrison** [HungryProton/scatter#182]
Loving this addon. How can I disable the orange box indicating the scatter shape in the scene editor?
<img width="1099" alt="Screenshot 2024-01-16 at 10 57 57 PM" src="https://github.com/HungryProton/scatter/assets/87624649/21f42446-5ae7-4a89-b32c-b4e7c92248de">

**Comment by florianvazelle** [comment]
You can disable the ScatterShape Gizmo in the View > Gizmos menu

![Screenshot_20240117-091503__01.jpg](https://github.com/HungryProton/scatter/assets/23208753/b347f630-8cb6-41e3-8493-92b3ca07a676)

Or you can disable it globally in Projects Settings > Addons > Proton Scatter menu

![Screenshot_20240117-091514__01.jpg](https://github.com/HungryProton/scatter/assets/23208753/9c1dd6a9-d06d-4b00-b057-b76ac8e09bfc)

**Comment by Preston-Harrison** [comment]
Thanks
