### ISSUE TITLE
Duplicating ProtonScatter node results in a crash.

### ISSUE THREAD

**Issue by verypleasentusername** [HungryProton/scatter#186]
self epxlanatory title. Console doesn't show any errors. 

i used godot 4.2.2 Windows 10, forward+.

**Comment by verypleasentusername** [comment]
it appears this is somehow connected to "project on colliders", without it no crash happens.

**Comment by TCROC** [comment]
I was able to reproduce this.  Also using the "project on colliders".  Workaround is to temporary disable "project on colliders" when duplicating. as @verypleasentusername also pointed out.

**Comment by sebastianrueckerai** [comment]
Happens for me as well!

**Comment by Minoqi** [comment]
Yup had that issues too. Can duplicate children fine but not the parent ProtonScatter node

Edit: Spelling

**Comment by verypleasentusername** [comment]
somehow this is connected to "force reload on scene load" parameter, with it unchecked also no crash

**Comment by HungryProton** [comment]
Sorry for the delay, this should be fixed in https://github.com/HungryProton/scatter/commit/7ae367f5a90c47fe19dc8a6738874fa900bd1e5e

Don't hesitate to re-open this issue if the problem persists.
