### ISSUE TITLE
Godot 4.2.1 - On reload of project, all ProtonScatter nodes change to disabled

### ISSUE THREAD

**Issue by mattboy115** [HungryProton/scatter#196]
I have been learning the ins and outs of Scatter and I really like it but there is a problem with being able to save and quit my project. Because when I return all the ProtonScatter nodes have changed their "enabled" attribute to false. The only thing I can think of to get by this in some way is to use code to change all those nodes to enable on ready, though code. But that would only work when the game plays. That doesn't help the problems in the editor. I've heard a couple other people have this same issue.

**Comment by fidojones** [comment]
I solved disabling the "enabled" variable in file src/scatter.gd in the funtion _exit_tree like this:

func _exit_tree():
	#enabled = false

**Comment by HungryProton** [comment]
Oh good catch, that was not supposed to be part of the commit, I'll push a fix
