### ISSUE TITLE
Scatter does not keep the transform of the duplicate items

### ISSUE THREAD

**Issue by fire** [HungryProton/scatter#2]
Transforms get reset.

![image](https://user-images.githubusercontent.com/32321/68548470-42e34f80-03a2-11ea-88d2-4f37614871b7.png)

**Comment by HungryProton** [comment]
Should be fixed in 42fc771931822ccc8ba218b2d5485525c7e7002d

**Comment by HungryProton** [comment]
definitive fix in 8f81bd781bd656c2a95cd8e4244aa977a715f76d
