### ISSUE TITLE
Add transformation modifier for constant offsets

### ISSUE THREAD

**Issue by addmix** [HungryProton/scatter#20]
Allows for fixes/changes in how prop placement works, such as fencing

![image](https://user-images.githubusercontent.com/38119387/103577903-daeba480-4e92-11eb-8fd2-d5d1b96f8a18.png)

**Comment by HungryProton** [comment]
Should be easy to add, I'll see what I can do as soon as I got time.

**Comment by HungryProton** [comment]
Added in e45edd4c508759f6aee778537751c3cb0c4ab95a
