### ISSUE TITLE
Getting error : Adding 'CollisionShape3D' as child to '' will make owner '' inconsistent.

### ISSUE THREAD

**Issue by eveningdreamer** [HungryProton/scatter#200]
I'm trying to use the scatterplugin, and it's been working great, but I get a weird error on game load (and the loading takes a while because I use quite a lot of scatters).

I get this error for every single scatter item I use in the game:

W 0:00:04:0639   scatter_util.gd:460 @ get_collision_data(): Adding 'CollisionShape3D' as child to '' will make owner 'leaf_tree_01' inconsistent. Consider unsetting the owner beforehand.
  <C++ Source>   scene/main/node.cpp:1427 @ add_child()
  <Stack Trace>  scatter_util.gd:460 @ get_collision_data()
                 scatter.gd:446 @ _update_split_multimeshes()
                 scatter.gd:720 @ _on_transforms_ready()

I've tried removing the collisionshapes, but then there's no more collisions to the items (even with "add static collider" active). I've tried making the staticbody the root of the loaded item but it didn't change the error.

I'm at a loss about what to do to fix the error. The game still works and plays, but loading the game takes a long time.

I'm quite new to this whole gamedev thing, so I'm probably doing something wrong, but I don't know what.

Thanks in advance for any help!

**Comment by HungryProton** [comment]
I'll try to look into it, if you can provide a minimum reproduction project that would help a lot. I need to be able to recreate the issue on my end to fix it. 
Either that, or screenshots of how your scenes are set up, (what you're trying to scatter, and screenshots of the scatter nodes inspector)

**Comment by HungryProton** [comment]
Actually, this is probably not specific on your project. You can probably ignore it for now.

**Comment by MartinFretigne** [comment]
Hello. I got the same error. 
I fixed it like that : 
```
diff --git a/addons/proton_scatter/src/common/scatter_util.gd b/addons/proton_scatter/src/common/scatter_util.gd
index ce4ef89..ec485f6 100644
--- a/addons/proton_scatter/src/common/scatter_util.gd
+++ b/addons/proton_scatter/src/common/scatter_util.gd
@@ -457,6 +457,7 @@ static func get_collision_data(item: ProtonScatterItem) -> StaticBody3D:
                        if child is CollisionShape3D:
                                # Don't use reparent() here or the child transform gets reset.
                                body.remove_child(child)
+                               child.owner = null
                                static_body.add_child(child)
 
        source.queue_free()
```

**Comment by HungryProton** [comment]
Thank you for the patch!
