### ISSUE TITLE
I can't open the demo scenes. Scene analysis error

### ISSUE THREAD

**Issue by IvailoBurov** [HungryProton/scatter#26]
Hi,
Which version of Godot do you use? I can't open the demo scenes with version 3.2.3.
By the way, no one scene can be opened by the project under Windows.

**Comment by HungryProton** [comment]
Works on 3.2.3 and 3.2.4 (possibly every 3.2.x, but I haven't tried).

Disabled the plugin, make sure the folder is named "scatter", not "scatter-master" or anything else GitHub my want to name it if you downloaded the archive, close the editor and open it again. Enable the plugin and it should work.

If that wasn't the issue, please paste the output log if there's any error messages.

**Comment by IvailoBurov** [comment]
Thanks for reply. After renaming of the folder it's ok.
