### ISSUE TITLE
Crash when scatter is played

### ISSUE THREAD

**Issue by fire** [HungryProton/scatter#3]
https://github.com/HungryProton/scatter/commit/a07e4a8235b572bd54f1c64eb718ca577534b309#r35887886

```
var _items : Array = Array()
var _exclusion_areas : Array = Array()
```

Fixes.

**Comment by HungryProton** [comment]
Thanks for the report, it's fixed in 1b6fc4ff0cd36f4ff48a3dcb8eb9a4cd233cb3ad
