### ISSUE TITLE
Write better documentation for custom types (modifier stack, transforms, etc)

### ISSUE THREAD

**Issue by addmix** [HungryProton/scatter#30]
General documentation improvements would be greatly appreciated, making it easier to make modifiers

**Comment by HungryProton** [comment]
I need to write a complete contribution guide later, https://github.com/HungryProton/scatter/wiki/Contribution-guide
Leave a comment in this issue if you need specific information to be added in the wiki.

**Comment by HungryProton** [comment]
Contribution guide updated, this should cover the basics https://github.com/HungryProton/scatter/wiki/Contribution-guide
