### ISSUE TITLE
Godot version 4.0

### ISSUE THREAD

**Issue by AndreaCatania** [HungryProton/scatter#36]
Do you have plan to support Godot 4.0?

**Comment by HungryProton** [comment]
I do! But not immediately. 

Last time I tried, Godot 4.0 (especially the GDScript part) crashed way to often on my machine (Ubuntu 20.04) and made development too annyoing.
That was more than a month ago though so maybe things got better in the meantime? I'll give it a try again but I don't set my hopes too high

**Comment by AndreaCatania** [comment]
Yee I see, well that's a good plugin that I would use, for the game I'm working on, if available for Godot 4. I hope to see it soon supported :)

**Comment by stryker313** [comment]
@HungryProton I recently ported my game to Godot 4, and it was decently stable. Maybe worth a try again. (11 mon. later)
Dev build - v4.0.dev.20211117

**Comment by HungryProton** [comment]
Yup, Godot 4 is getting more and more stable, I'm hoping to get a working version at the end of next month but no promises :no_mouth:  (I'm moving to another country at the moment which means, I'll probably only start working on this in a few weeks)

**Comment by jgillich** [comment]
I see there is a v4 branch, what's its status? Do you need help?

**Comment by HungryProton** [comment]
Yeah, porting the add-on is a lot longer than I thought, but that's also because I'm completely changing how the user defines the shapes where nodes are scattered and fixing some bad architecture decisions from the 3.x version. The modifier stack was reworked to be easier to use, too. 

It would be hard to coordinate at this point, but it shouldn't take too long before the first working version.

**Comment by tavurth** [comment]
I guess godot will be in Beta soon, very much looking forward to using your plugin there 🙏

**Comment by HungryProton** [comment]
I hope I can get it done around the beta release. The bulk of the work is done (on the `v4` branch), now it's mostly about bug fixing and UX improvement.

**Comment by sebastianrueckerai** [comment]
I am also making the jump to V4 and I cant wait for your awesome project to be available there! :D

**Comment by Trey2k** [comment]
> I hope I can get it done around the beta release. The bulk of the work is done (on the `v4` branch), now it's mostly about bug fixing and UX improvement.

Looking forward to this!

**Comment by HungryProton** [comment]
Current status is:
+ It works on Linux
+ There's a physics bug on Windows I still need to fix, in the `Project on colliders` modifier (the rest should work).
+ The folder structure needs to change to make it compatible with the asset lib

There's still a lot of optimization to do as well. Godot 4 supports compute shaders, some modifiers could benefit from that for example, but that can wait for after the asset lib.

**Comment by HungryProton** [comment]
Closing as v4 has been up and running for a while now and is available from the asset library.
