### ISSUE TITLE
Support StaticBodys & Colliders

### ISSUE THREAD

**Issue by JanWerder** [HungryProton/scatter#39]
It would be great if Scatter would support StaticBodys and Colliders and copy them from the source node to the MeshInstance, if that is possible.
Example hierarchy:
![image](https://user-images.githubusercontent.com/596986/110503017-0c375980-80fc-11eb-9309-c46e6d20a6c9.png)

**Comment by HungryProton** [comment]
You can disable instancing on the Scatter node, and it will copy the whole scene at the expense of batching.

**Comment by JanWerder** [comment]
Thanks for the explaination, but it doesn't seem to work for me (even after a rebuild).
It clones the MeshInstances but without its childs.
![image](https://user-images.githubusercontent.com/596986/110768293-6436a300-8257-11eb-8905-606ac1350ccc.png)
The scatter:
![image](https://user-images.githubusercontent.com/596986/110768343-7284bf00-8257-11eb-98af-a9484b89d4cb.png)
The ScatterItem:
![image](https://user-images.githubusercontent.com/596986/110768386-7adcfa00-8257-11eb-95c5-93c3d489bb62.png)

Am I doing something wrong?

**Comment by HungryProton** [comment]
Should be fixed in the latest master commit f03937a638958f5d451e1079a7376ece27841be7

**Comment by JanWerder** [comment]
Works great, thanks!
