### ISSUE TITLE
Add an option to hide the grid

### ISSUE THREAD

**Issue by Flavelius** [HungryProton/scatter#40]
Hi,
i cannot find an option to hide the orange grid, that currently overlays all scattered objects. 
It doesn't seem to have any use apart from showing the bounding area of the path. 
It would be nice to be able to hide only it, as hiding the gizmo via godot options also hides the path, which is not desired.

Edit: this seems to be mostly a godot bug. If the Scatter node is selected and deselected the toolbar options linger, which makes this grid stay in the world. To remove it another node has to be selected.
It would still be helpful to hide it to better see the geometry underneath it.

**Comment by HungryProton** [comment]
The last part is because the Scatter node inherits from the built-in Path node which also behaves like this when deselected.
The grid is mostly there as a visual clue when `Lock to Plane` is enabled, but it could use more options. I'll see what I can do about it.

**Comment by HungryProton** [comment]
Added in 6ba304de1cad78475a4910dde83c89d4fdf2e768 (latest commit of master)  
You now have an option panel on top of the viewport (I was running low on space on the top dock)

![image](https://user-images.githubusercontent.com/52043844/111303088-6b452300-8654-11eb-865c-ef5d10d4a44d.png)

Clicking the `Show extra options` button reveals hidden options, you can select `Always hide the grid` to completely disable it, or change its color to something more transparent if you want to keep it but make it less visible.
![image](https://user-images.githubusercontent.com/52043844/111303528-ea3a5b80-8654-11eb-9fcf-cd87327769ce.png)

You only have to do this once, settings are saved in `user://scatter_config.cfg` so they are shared across all projects using the add-on. Let me know if this works properly on your side.

**Comment by Flavelius** [comment]
This new panel looks good 👍 
And it seems to work as expected, thanks for the quick adjustments
One small thing i noticed, while on the topic, is that one side of the grid is always missing the bounding line for me (see left side; probably just a < instead of <= in some loop):
![grafik](https://user-images.githubusercontent.com/8841352/111309683-79973d00-865c-11eb-9953-3dd83e4365f7.png)

**Comment by HungryProton** [comment]
Should now be fixed in 4f8eaf0195208119b189896bb6c1bf4d0164369f
