### ISSUE TITLE
Error with Signals in curve_panel.gd

### ISSUE THREAD

**Issue by jitspoe** [HungryProton/scatter#44]
Hey, just grabbed latest mainline and I'm getting an error about "Signals" not being declared.  curve_panel.gd didn't exist when I tried this plugin a couple months ago, so I'm guessing this is new WIP code?  Or maybe something failed to get checked in?

**Comment by HungryProton** [comment]
Oops, that's some code ported from another project, it shouldn't use the Signal object at all, that's an autoload I'm using on my end. Should be fixed on 3092778bcd753c8edf2a08ce2330ec33e9ac1bea
