### ISSUE TITLE
Imported mesh data get duplicated

### ISSUE THREAD

**Issue by jitspoe** [HungryProton/scatter#45]
If you use scatter without multimesh, it creates copies of the mesh data instead of creating an external reference (meaning imported meshes won't update if you edit them).  Seems this is caused by the recursive set owner.   I changed _set_owner_recursive to just set the owner on the node and not its children, and that seemed to fix it.  Not sure if there's a reason for setting the owner on the children.

**Comment by HungryProton** [comment]
Looks like this issue was introduced in f03937a638958f5d451e1079a7376ece27841be7
I'll push a fix tonight

**Comment by jitspoe** [comment]
Bam!  You are on top of things!
