### ISSUE TITLE
Scatter Addon Not Working With Shader Material

### ISSUE THREAD

**Issue by stryker313** [HungryProton/scatter#46]
[ScatterBug.zip](https://github.com/HungryProton/scatter/files/6780859/ScatterBug.zip)

In the editor, the scatter item displays correctly and uses a multimesh instance.
In the game, the scatter items don't have a material when using a multimesh instance.

Disabling "use instancing" will allow the materials to work, however this isn't a performance friendly option for massive amounts of items.

I do not know if this is intentional(I would assume not, since you can see the scatter items WITH their respective materials in the editor while using a multimesh instance)

Using a material/geometry override for the material can be a simple workaround, however it does not work if your item has multiple materials( so this hack would work for something like grass, but if you wanted to do something like a tree, no go.)

If upon loading the project the trees have no material in the editor, click on the main scatter nodes to reload the materials.

Again, if it works within the editor I would assume its a glitch/bug, but unsure

**Comment by HungryProton** [comment]
Thanks for providing the test project, I couldn't have reproduced the issue on my end otherwise.

The bug only happens when using obj files (maybe other formats too?), but not when using gltf2. I'm looking into it but I'm not sure how I'm going to fix that.

**Comment by HungryProton** [comment]
Commit 6bfd79b88b41b8d17aa2a0bfb298c4fdd08c26de fixes the issue on my side. Let me know if this works properly

**Comment by stryker313** [comment]
Works beautifully. Thanks. Great job on the addon btw.
