### ISSUE TITLE
Can I control "Instance Count" programmatically?

### ISSUE THREAD

**Issue by telmotrooper** [HungryProton/scatter#48]
I'm developing a 3D platformer and have used your plugin and the grass from the demo (with proper credit) in the game. I'm using 4000 instances of the MultiMeshInstance in my scene but I'd like to allow the player to decrease  the amount of grass rendered to increase performance.

I haven't found a way to access the "Instance Count" variable in the "Distribute Inside (Random)" modifier programmatically in the documentation. Is this possible? Thank you!

![image](https://user-images.githubusercontent.com/9438853/126235847-bef38267-1b0d-4dcc-a05c-310a93a14112.png)

**Edit:** [The repo with the game](https://github.com/telmotrooper/squash-the-creeps) if anyone is interested.

**Comment by HungryProton** [comment]
:thinking:  Probably not, well, you could try something like this (assuming the distribute modifier is the first one in the list):
```
scatter_node.modifier_stack.stack[0].instance_count = 2000
scatter_node._do_update()
```

But I haven't planned for this use case, I should look into making a proper API for that.

**Comment by telmotrooper** [comment]
@HungryProton Had no success here, tried `modifier_stack.stack[0].instance_count = 2000` but `_do_update()` apparently is not found. If I call `update()` or `_set_instancing(true)` nothings happens, if I call `full_update()` all the grass disappears.

Guess I'm out of luck... Will probably just put an option to completely remove the grass for the time being.

Thanks for the help anyway. 🙂️

**Comment by HungryProton** [comment]
`_do_update` was added in an update a few days ago so you need to get the latest version on github. If you can't update, then you need to disable the `Disable updates in game` on the scatter node, otherwise the _update function is ignored. Calling `full_update` during a game will probably break a bunch of stuff related to the physic engine so better not call that function

**Comment by telmotrooper** [comment]
It seems I was using version `2.5.1`, which is what shows as latest release in the repository:
![image](https://user-images.githubusercontent.com/9438853/126571676-2c86c481-9910-492b-8de9-93705ea014b9.png)
 I've just cloned the latest of Scatter and was indeed able to reduce the amount of grass in real time using `modifier_stack.stack[0].instance_count` and `_do_update()`.

Thank you a lot!

**Comment by HungryProton** [comment]
Nice, I'm glad it worked!
I updated the release page just in case, I forget about it every time.
