### ISSUE TITLE
"Project on Floor/Align with Floor normal" doesn't account for object's global rotation

### ISSUE THREAD

**Issue by realgdman** [HungryProton/scatter#50]
Hello, thank you for great addon.
I'm using Godot 3.4.beta4 and latest Scatter

I've tried to create roads with it, and noticed that "Project on Floor" / "Align with Floor normal" doesn't take into account the global rotation of whole object.
You can notice on screenshot that panels "Distributed along the Path" correctly, but rotated instance have every individual brick overturned.

![image](https://user-images.githubusercontent.com/83962805/130338656-9f93805d-8e90-467b-ad2d-401b9d15dadc.png)

In my case, there is workaround, because I care only about rotation around Y axis, in project_on_floor.gd:

	if align_with_floor_normal:
		var gt: Transform = transforms.path.get_global_transform()
		t = _align_with(t, hit.normal.rotated(Vector3.UP, -gt.basis.get_euler().y))

But I don't know what would be general solution.
Added simple repro project. Thanks again.
[ScatterNormalsBug.zip](https://github.com/HungryProton/scatter/files/7026427/ScatterNormalsBug.zip)

**Comment by realgdman** [comment]
Ok, I found better workaround, which accounts for rotations and scale(-1) too. Will test more tomorrow.

			if align_with_floor_normal:
				var gt: Transform = transforms.path.get_global_transform()
				t = _align_with(t, gt.basis.xform_inv(hit.normal))

**Comment by HungryProton** [comment]
Select your `Scatter Item` node and disable the `Ignore initial rotation` option
![scatter_item_options](https://user-images.githubusercontent.com/52043844/130347385-4697ce36-3f84-484d-a120-dd15b17ef89f.png)

Let me know if that works

**Comment by realgdman** [comment]
No, I haven't managed "Ignore rotation" to work.
From my understanding, _transform is local to Scatter node, but normal returned from space_state.intersect_ray is in global coordinates.
In my case, I have several instances of scene with Scatter, and each instance is rotated arbitrary
TerrainScene
-TileScene (0 deg)
-TileScene (45 deg)

with
TileScene
-Scatter
-StaticBody
--CollisionShape

Say I have instance 1
![image](https://user-images.githubusercontent.com/83962805/130355387-3b0a159b-e706-4dc7-9c3d-0f819bbbc417.png)

Now if I duplicate it, rotate 50 degrees and duplicate again, it will rotate all bricks on the path to the same 50 degrees
![image](https://user-images.githubusercontent.com/83962805/130355555-4f8fad28-ebdb-4486-a378-f9cb9d00c9a5.png)
Sometimes it looks OK in editor, but still messed ingame
![image](https://user-images.githubusercontent.com/83962805/130355931-35b60e3b-8472-46a9-874c-de1ed84ab586.png)

With my workaround in second post, I can have arbitrary rotations
![image](https://user-images.githubusercontent.com/83962805/130355961-42c1952f-2729-45b3-86f6-b070e0d738de.png)

[ScatterNormals.zip](https://github.com/HungryProton/scatter/files/7027370/ScatterNormals.zip)

**Comment by HungryProton** [comment]
Indeed, that's a bug. You can submit a PR, and I'll merge it, or I can do the fix directly, as you want

**Comment by realgdman** [comment]
Thanks again for great tool!
