### ISSUE TITLE
There is no way for me to compensate your incredible work.

### ISSUE THREAD

**Issue by brandonschmeidler** [HungryProton/scatter#62]
I'm sorry for posting this in the issues section. I just don't have a Twitter account and I would really like to, at the very least, give you 10-15 bucks for your hard work. I couldn't find any sort of patreon or donate link anywhere. If you're not interested I understand, but I like to support game developers that are willing to do all of this work and give it away for nothing. I'm sure there are many other people that would be more than happy to support your work. Just a thought. Feel free to close this. There is no _real_ issue. The addon itself is pretty flawless so far. Does what it says on the tin and it works well and fast.

**Comment by HungryProton** [comment]
Hi, thanks for your kind words! I'm glad the addon works great for you :) 
I do have a kofi account for donations (it uses PayPal for payment), but I realize I never really advertised it anywhere, and I don't really post much there either.

Here's the link: https://ko-fi.com/hungryproton

**Comment by brandonschmeidler** [comment]
Awesome! I got you up to 30 heart coffee things now. 😄
