### ISSUE TITLE
Intend to support frustrum or distance culling?

### ISSUE THREAD

**Issue by tavurth** [HungryProton/scatter#63]
Playing around with this and I love the way you've setup the modifiers, very smart!

Godot 4.x already supports Occlusion culling, but in Godot 3.x I'm not sure if frustrum culling is applied to `MultiMeshInstance`.

Usually I get around this by adding a `VisibilityNotifier` and disabling the object when it becomes invisible from the camera.

Since we're using `MultiMeshInstance` perhaps splitting the terrain into groups and allowing hiding would work better.

Any idea about how we could support something like that?

**Comment by HungryProton** [comment]
Thanks!
In 3;x, you already get frustrum and distance culling for every nodes. Keep in mind though that even if a single instance of the Multimesh is visible on screen, then the entire Multimesh will be processed as if it was a single object. (See this page: https://github.com/HungryProton/scatter/wiki/Multimesh-and-Duplicates#warning-about-multimesh )

One way around it is to either use multiple Scatter nodes but it's not the ideal solution for really large areas. I was planning to add a feature that splits the Multimesh along a grid but that's something I never started to work on.

**Comment by Norodix** [comment]
Hey, 
Distance and frostum culling are now supported. The Split multimesh function was added to allow frostum culling. Visibility range settings allow distance culling as well as some crude LOD.
See
https://github.com/HungryProton/scatter/pull/86
https://github.com/HungryProton/scatter/pull/80
