### ISSUE TITLE
Error,  "Invalid call. Nonexistent function 'lock_to_plane' in base 'PanelContainer'" when trying to edit curve.

### ISSUE THREAD

**Issue by AnnabelleLewis** [HungryProton/scatter#74]
Whenever I try to edit the curve3d used by a scatterer node, I get the error 
`res://addons/scatter-master/src/tools/path_gizmo/scatter_path_gizmo_plugin.gd:156 - Invalid call. Nonexistent function 'lock_to_plane' in base 'PanelContainer`'
I also cannot drag the points or edit the curve in any way.  I am working in a blank project with just the Scatter add-on installed, and am using Godot 3.4.3

**Comment by HungryProton** [comment]
The folder is named `scatter-master` and that's causing the issue. Rename it to `scatter` only, and it should work.
