### ISSUE TITLE
i have a script that disables collision on ready

### ISSUE THREAD

**Issue by Favkis** [HungryProton/scatter#77]
it works if object is normally placed into scene, but doesn't if it's placed with scatter, how do I make it work?
I disable collision by $CollisionShape.disabled=true and it doesnt work inside of Scatter.

**Comment by HungryProton** [comment]
Did you disable the `Use instancing` option on the scatter node? If not, collisions will be ignored.

**Comment by Favkis** [comment]
> 

yes, that's why I'm trying to disable them, I have thoughsands of rocks and those added by scatter dont have their collisionshape.disabled as true

**Comment by Favkis** [comment]
oh wait, it maybe works actually even at ready and it changed lod, oh... nvm sorry for this report

**Comment by HungryProton** [comment]
No worries, feel free to re-open the issue if it turns out to be a scatter bug.
