### ISSUE TITLE
Add option to not save position of scatter objects to disk

### ISSUE THREAD

**Issue by addmix** [HungryProton/scatter#90]
Scenes with large amounts of scattered objects can be in the hundreds of megabytes, it would be very useful if there was an option that generated all scattered objects from the saved seed at runtime. This is one of the main complaints I've seen people have of this plugin.

**Comment by HungryProton** [comment]
That's just a matter of not setting the owner of the new nodes, it should be easy to add an option. I should have some time during this week (unless someone else wants to work on it)

**Comment by addmix** [comment]
Yeah, when you have a multimesh containing hundreds of thousands of positions it starts to add up. Would be very nifty to keep install size low.

**Comment by Norodix** [comment]
Solved by https://github.com/HungryProton/scatter/pull/91
