### ISSUE TITLE
Godot V4 non-instance throw

### ISSUE THREAD

**Issue by Remi123** [HungryProton/scatter#95]
Version Godot V4 beta 6
Scatter commit : 68eaa8b7b2e665f0b46086863333b11375c2a979
   ( Latest one on branch v4 as of nov23)

Scene : showcase.tscn
Attempted to use non-instancing of the MainGround ( basically LargeRock ) to get the collision shapes and try to walk over it. Or by creating a fence. Basically I'm trying to use Scatter with non-instance. Tried this on a new scene and same error.

Error thrown : Invalid type in function 'set_owner_recursive' in base 'GDScript'. The Object-derived class of argument 2 (null instance) is not a subclass of the expected argument class.

![image](https://user-images.githubusercontent.com/16803994/203825287-9a7bc65f-eddc-4427-a5f6-26d8b29684f0.png)

![image](https://user-images.githubusercontent.com/16803994/203825404-4162326a-4c38-4380-894a-674c9c0bdc7a.png)

From what I've gather get_edited_scene_root() is null once we enter play mode. 

I've attempted to replace every get_edited_scene_root() with get_tree().get_current_scene(), and the content got generated, but with a small offset of about 4 meter to the right. Didn't have time to investigate further.

**Comment by Remi123** [comment]
Further inspection:

The generation of the non-instance in the editor works great, as seen here : 
![image](https://user-images.githubusercontent.com/16803994/203875920-84e2b8c5-d782-42bd-a7e4-ffb887d9c841.png)
The large rocks have wireframe since I display collisionshapes in the editor. In play mode it throw. as described earlier.

This is when I run the scene when everything is set to use instance : 
![image](https://user-images.githubusercontent.com/16803994/203876329-a3d5d0c7-3687-441c-b77f-8a1f07a29e0c.png)

edit:
Just to be clear, I needed to disabled every Project on collider modifier since the grounds doesn't have collider since we use instance

**Comment by HungryProton** [comment]
For the first bug in play mode, that's fixed in the latest v4 commit (8f36dcb21ea9d24a304ed9ada8f02f31190646fe)

Not sure what causes the 4m offset, but I'll look into it

**Comment by Remi123** [comment]
Thanks for investigating. I'll take a look at the fixes.

My mistake for the 4m offset, it's due to disabling the "project on collider" when investigating the bug, then I got an emergency and when I come back I forgot about my changes.

**Comment by Remi123** [comment]
I can confirm it fixed the bug. 
![image](https://user-images.githubusercontent.com/16803994/204003513-714e31c7-6363-410a-8ea8-f935838a822c.png)

Thanks for fixing it quickly :)
