### ISSUE TITLE
Current v4 branch build does not load, and can crash beta 6 on project load

### ISSUE THREAD

**Issue by Ophiolith** [HungryProton/scatter#97]
Adding Scatter as an add-on via the usual methods, either by git-clone or copying the project into a subfolder on a blank project does not currently work. Enabling the plugin via project settings works, but scatter nodes are not callalble from the node selector either by search or navigating the tree, Attempting to load any of the included TSCNs will fail with a generic loading error. I have tried renaming the folder to 'scatter' as per the old naming schema, this does not make any difference.

Opening a minimal reproduction project with Scatter loaded can sometimes cause Godot to crash-to-desktop, though I have not been able to get this to reproduce reliably.

As a minimal reproduction project with Scatter installed exceeds Github's filesize limit, I have uploaded one to my Dropbox: https://www.dropbox.com/s/yyydqnul0fr4vox/ScatterTest.zip?dl=0

**Comment by HungryProton** [comment]
Try renaming it to `proton_scatter` instead (add-on was renamed to avoid confusion with Zylann's own scatter which is older).

If that doesn't work, please include the exact error message (if any) and I'll look into it.

**Comment by Ophiolith** [comment]
> Try renaming it to `proton_scatter` instead (add-on was renamed to avoid confusion with Zylann's own scatter which is older).
> 
> If that doesn't work, please include the exact error message (if any) and I'll look into it.

Yep, that solved it, changing it to proton_scatter fixed it altogether. Thank you for answering that, much appreciated!

**Comment by HungryProton** [comment]
Thank you for the report. I will change the add-on folder structure soon to avoid this issue (and make it compatible with the asset lib requirements as well).
