### ISSUE TITLE
Suggestion: generate collision model

### ISSUE THREAD

**Issue by Favkis** [HungryProton/scatter#99]
Can you make it so that we can use instancing for drawing, but then generating one staticbody with collisionshape that has all of the collisions for objects? Like for example populating forest with trees and then having single staticbody with all trees collision shapes inside?

**Comment by addmix** [comment]
Or, for performance it may be better to add these large amounts of collision shapes through the physics server, as scatters aren't really node based.

**Comment by HungryProton** [comment]
I will probably start working on this once I'm done with #119 and #121

**Comment by HungryProton** [comment]
Added in v4 (ce1d56778001484ec32d4333b67cace60b3e4d7b)
